on:
  push:
    branches:
      - master
jobs:
  package-extension:
    - uses: actions/checkout@v2
      steps:
        - name: Package
          run: |
            chmod +x ./build.sh
            ./build.sh
          shell: bash

