on:
  push:
    branches:
      - master
jobs:
  package-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Package
        run: |
          chmod +x ./build.sh
          ./build.sh
        shell: bash
      - name: Create Release
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1.12.0
        with:
          artifact: ./sprite-variant.aseprite-extension
