on:
  push:
    branches:
    - master
jobs:
    package-extension:
      runs-on: ubuntu-latest
      steps:
        - name: Package
          run: |
            chmod +x ./build.sh
            ./build.sh
          shell: bash
