on:
  push:
    branches:
      - master
jobs:
  package-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Package
        run: |
          chmod +x ./build.sh
          ./build.sh
        shell: bash

