on:
  push:
    branches:
      - master
jobs:
  package-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Package
        run: |
          chmod +x ./build.sh
          ./build.sh
        shell: bash
      - name: Release
      - name: Create Release
        # You may pin to the exact commit or the version.
        # uses: ncipollo/release-action@a2e71bdd4e7dab70ca26a852f29600c98b33153e
        uses: ncipollo/release-action@v1.12.0
        with:
          artifact: ./sprite-variant.aseprite-extension
