on:
  push:
    tags:
      - '*'
jobs:
  package-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Package
        run: |
          chmod +x ./build.sh
          ./build.sh
        shell: bash
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "sprite-variant.aseprite-extension"
